# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

imports:
  root: __package__.yml
  commons: ../commons.yml
  sheets: ../sheets.yml

service:
  auth: true
  display-name: Space Config
  base-path: /spaces/configs
  endpoints:
    list:
      path: ""
      method: GET
      docs: Returns all space configs for an account
      display-name: List space configs
      request:
        name: ListSpaceConfigsRequest
        query-parameters:
          environmentId: optional<commons.EnvironmentId>
      response: ListSpaceConfigsResponse
      errors: 
        - commons.BadRequestError

    replace:
      path: ""
      method: PUT
      docs: >-
        Replaces an existing Space Config and optionally migrates all spaces
        using the config
      display-name: Replace a space config
      request:
        name: ReplaceSpaceConfigRequest
        query-parameters:
          migrate: optional<boolean>
        body: SpacePatternConfig
      response: SpacePatternResponse
      errors: 
        - commons.BadRequestError

    create:
      path: ""
      method: POST
      docs: Creates a new Space Config
      display-name: Create a space config
      request: SpacePatternConfig
      response: SpacePatternResponse
      errors: 
        - commons.BadRequestError

types: 
  ListSpaceConfigsResponse:
    properties:
      data: optional<list<SpacePattern>>
  
  SpacePatternResponse: 
    properties: 
      data: SpacePattern

  SpacePatternConfig:
    docs: Properties used to create a new Space Config
    properties:
      slug: string
      name: string
      blueprints: list<Blueprint>
      actions: optional<list<commons.Action>>
  
  Blueprint:
    docs: Properties used to create a new Blueprint
    properties:
      slug: string
      name: string
      primary: optional<boolean>
      sheets: list<sheets.SheetConfig>
  
  SpacePattern: 
    extends: SpacePatternConfig
    properties: 
      id: commons.SpaceConfigId
