# yaml-language-server: $schema=https://raw.githubusercontent.com/fern-api/fern/main/fern.schema.json

imports:
  commons: commons.yml
  agents: agents.yml

service:
  auth: true
  base-path: /environments
  endpoints:
    list:
      path: ""
      method: GET
      docs: Get all environments
      display-name: List environments
      response: ListEnvironmentsResponse
      examples:
        - response:
            body: 
              data:
              - id: us_env_hVXkXs0b
                accountId: us_acc_uj6s91wc
                name: dev
                isProd: false
                newSpacesInherit: false
                guestAuthentication:
                  - magic_link

    create:
      path: ""
      method: POST
      docs: Create a new environment
      display-name: Create an environment
      request: EnvironmentConfig
      response: Environment
      examples:
        - request: $EnvironmentConfig.Example0
          response:
            body: $Environment.Example0

    get:
      path: /{environmentId}
      method: GET
      docs: Returns a single environment
      display-name: Get an environment
      path-parameters:
        environmentId:
          docs: ID of the environment to return
          type: string
      response: Environment
      examples:
        - path-parameters:
            environmentId: $commons.EnvironmentId.Example0
          response:
            body: $Environment.Example0

    update:
      path: /{environmentId}
      method: PATCH
      docs: Updates a single environment, to change the name for example
      display-name: Update an environment
      path-parameters:
        environmentId:
          docs: ID of the environment to update
          type: string
      request: EnvironmentConfig
      response: Environment
      examples: 
        - path-parameters:
            environmentId: $commons.EnvironmentId.Example0
          request: $EnvironmentConfig.Example0
          response:
            body: $Environment.Example0

    getAgentLogs:
      path: /{environmentId}/logs
      method: GET
      display-name: Get all agent logs for an environment
      path-parameters:
        environmentId: string
      request:
        name: GetAgentLogsRequest
        query-parameters:
          pageSize:
            docs: Number of logs to return in a page (default 20)
            type: optional<integer>
          pageNumber:
            docs: Based on pageSize, which page of records to return
            type: optional<integer>
      response: agents.GetAgentLogsResponse
      examples:
        - path-parameters:
            environmentId: $commons.EnvironmentId.Example0
          request: 
            query-parameters:
              pageSize: 5
              pageNumber: 10
          response:
            body: $agents.GetAgentLogsResponse
types:
  ListEnvironmentsResponse:
    properties:
      data: optional<list<Environment>>
  
  EnvironmentResponse:
    properties:
      data: optional<Environment>
  
  Environment: 
    extends: EnvironmentConfig
    properties: 
      id: commons.EnvironmentId
      accountId: optional<commons.AccountId>
    examples:
      - name: Example0 
        value: 
          name: dev
          isProd: false
          newSpacesInherit: false
          guestAuthentication:
            - magic_link
          id: $commons.EnvironmentId.Example0
          accountId: $commons.AccountId.Example0

  EnvironmentConfig:
    docs: Properties used to create a new environment
    properties:
      name:
        docs: The name of the environment
        type: string
      isProd:
        docs: Whether or not the environment is a production environment
        type: boolean
      newSpacesInherit:
        docs: >-
          Whether or not new spaces have the option to copy files and guests
          from existing spaces, defaults to false
        type: optional<boolean>
      guestAuthentication: optional<list<GuestAuthentication>>
    examples:
      - name: Example0 
        value: 
          name: dev
          isProd: false
          newSpacesInherit: false
          guestAuthentication:
            - magic_link

  GuestAuthentication:
    docs: The type of authentication to use for guests
    enum:
      - shared_link
      - magic_link
      